name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_test_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
      - name: Cache MSL
        id: cache-msl
        uses: actions/cache@v4
        with:
          path: packages/morsel/public/ModelicaStandardLibrary_v4.1.0.zip
          key: ${{ runner.os }}-msl-v4.1.0
      - name: Install Dependencies
        run: npm ci
      - name: MSL Download Check
        run: |
          mkdir -p packages/morsel/public
          if [ "${{ steps.cache-msl.outputs.cache-hit }}" != 'true' ]; then
            curl -L https://github.com/modelica/ModelicaStandardLibrary/releases/download/v4.1.0/ModelicaStandardLibrary_v4.1.0.zip -o packages/morsel/public/ModelicaStandardLibrary_v4.1.0.zip
          fi
      - name: Run Build
        run: npx lerna run build
      - name: Run Tests
        run: npx lerna run test
      - name: Run Lint
        run: npx lerna run lint
