name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build_test_lint_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
      - name: Cache MSL
        id: cache-msl
        uses: actions/cache@v4
        with:
          path: packages/morsel/public/ModelicaStandardLibrary_v4.1.0.zip
          key: ${{ runner.os }}-msl-v4.1.0
      - name: Install Dependencies
        run: npm ci
      - name: MSL Download Check
        run: |
          mkdir -p packages/morsel/public
          if [ "${{ steps.cache-msl.outputs.cache-hit }}" != 'true' ]; then
            curl -L https://github.com/modelica/ModelicaStandardLibrary/releases/download/v4.1.0/ModelicaStandardLibrary_v4.1.0.zip -o packages/morsel/public/ModelicaStandardLibrary_v4.1.0.zip
          fi
      - name: Run Build
        run: npx lerna run build
      - name: Run Tests
        run: npx lerna run test
      - name: Publish Test Report
        uses: ctrf-io/github-test-reporter@v1
        with:
          report-path: "./ctrf/ctrf-report.json"
        if: always()
      - name: Run Lint
        run: npx lerna run lint
      - name: SPA fallback for GitHub Pages
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        run: cp packages/morsel/build/client/index.html packages/morsel/build/client/404.html
      - name: Deploy Morsel
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        with:
          personal_token: ${{ secrets.MODELSCRIPT_MORSEL_DEPLOY_PAT }}
          external_repository: modelscript-morsel/modelscript-morsel.github.io
          publish_dir: ./packages/morsel/build/client
